---
title: "Anomaly Detection With Google Trends: Vote"
output: html_notebook
---

```{r create df using google trends data}
#install.packages("gtrendsR")
library(gtrendsR)
#create df with google trends data
google_trends_df = gtrends(
                   c("vote"), #keywords -- start with one
                   gprop = "web", #choose: web, news, images, froogle, youtube
                   geo = c("US"), #only pull results for US
                   time = "today+5-y")[[1]] #timeframe

```

```{r plot in ggplot2}
library(tidyverse)
#visualize with ggplot (optional but useful if you're choosing between keywords)
ggplot(data=google_trends_df, 
       aes(x=date, y=hits, group=keyword, col=keyword)) +
        geom_line() + 
        theme_bw() +
        labs(title = "Google Trends Data", 
             subtitle="United States search volume", 
             x="Time", y="Relative Interest")
```


```{r anomalize}
#install.packages("tidyverse")
#install.packages("anomalize")
library(tidyverse)
library(anomalize)

#prepare data
google_trends_df_tbl = google_trends_df %>%
                   mutate(date=lubridate::ymd(date)) %>%
                   tbl_df()

#anomalize!

# STL + IQR Anomaly Detection
google_trends_df_tbl %>%   
    time_decompose(hits, method = "stl"
                   , trend = "1 year"
                   ) %>%
    anomalize(remainder, method = "iqr") %>%
    time_recompose() %>%
    # Anomaly Visualization
    plot_anomalies(time_recomposed = TRUE) +
    labs(title = "Google Trends Data - STL + IQR Method",x="Time",y="Relative Interest", subtitle = "United States search volume for 'Vote' in the last 5 years"
         )

# Twitter + IQR Anomaly Detection
google_trends_df_tbl %>%   
    time_decompose(hits, method = "twitter"
                   , trend = "1 year"
                   ) %>%
    anomalize(remainder, method = "iqr") %>%
    time_recompose() %>%
    # Anomaly Visualization
    plot_anomalies(time_recomposed = TRUE) +
    labs(title = "Google Trends Data - Twitter + IQR Method",x="Time",y="Relative Interest", subtitle = "United States search volume for 'Vote' in the last 5 years"
         )


# Twitter and GESD
google_trends_df_tbl %>%   
    time_decompose(hits, method = "twitter",trend = "1 year") %>%
    anomalize(remainder, method = "gesd") %>%
    time_recompose() %>%
    # Anomaly Visualization
    plot_anomalies(time_recomposed = TRUE) +
    labs(title = "Google Trends Data - Twitter + GESD Method",x="Time",y="Relative Interest", subtitle = "United States search volume for 'Vote' in the last 5 years"
         )

# look at how anomaly detection works
google_trends_df_tbl %>% 
  time_decompose(hits, method = "twitter", 
                 frequency = "1 year", trend = "1 year") %>%
  anomalize(remainder, method = "gesd", alpha = 0.05, max_anoms = 0.2) %>%
  plot_anomaly_decomposition() 

```



